### ISSUE TITLE
Relative image urls breaking the app

### ISSUE THREAD

**Issue by dabeeeenster** [dirkmc/press#1]
Hi,

I had to add: 

GET      /press/images/         staticDir:public/images

to the bottom of my routes file - I had images referenced in my CSS that was breaking the app. You should maybe add this to the gotchas along with the CSS and JS directives?

**Comment by dirkmc** [comment]
Thanks for the bug report.
Could you be a bit more specific... you said you had images referenced in your CSS file that was breaking the app. What do you mean by breaking the app?
As far as I know you should be able to include images without a problem. Could you include the piece off CSS code that causes the problem?
Thanks

**Comment by dabeeeenster** [comment]
Hi,

Sorry - not a very helpful issue report from me! I have the following fragment in a CSS file that is being included in press:

#main {
    background: url("../images/contentAreaRepeat.png") top center repeat-y;
    padding: 0 40px 20px 40px;
    width: 880px;
    margin-left: auto;
    margin-right: auto;
    top: -40px;
    position: relative;
    margin-bottom: -120px;
}

If I take out 

GET /press/images/ staticDir:public/images

I get the following error:

@6455p04no
Internal Server Error (500) for request GET /press/images/contentAreaRepeat.png

Execution exception (In {module:press-1.0.9}/app/press/Compressor.java around line 109)
PressException occured : Attempt to add the same CSS file to compression twice: 'reset.css' Check that you're not includ
ing the same file in two different #{press.stylesheet} tags

play.exceptions.JavaExecutionException: Attempt to add the same CSS file to compression twice: 'reset.css'
Check that you're not including the same file in two different #{press.stylesheet} tags
        at play.templates.BaseTemplate.throwException(BaseTemplate.java:88)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:226)
        at play.templates.GroovyTemplate$ExecutableTemplate.invokeTag(GroovyTemplate.java:330)
        at /include/header.html.(line:6)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
        at play.templates.FastTags._include(FastTags.java:277)
        at play.templates.FastTags$_include.call(Unknown Source)
        at /app/views/publicSite.html.(line:1)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:236)
        at play.mvc.results.NotFound.apply(NotFound.java:48)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:302)
        at Invocation.HTTP Request(Play!)
Caused by: press.PressException: Attempt to add the same CSS file to compression twice: 'reset.css'
Check that you're not including the same file in two different #{press.stylesheet} tags
        at press.Compressor.add(Compressor.java:109)
        at press.Plugin.addCSS(Plugin.java:69)
        at press.Plugin$addCSS.call(Unknown Source)
        at {module:press-1.0.9}/app/views/tags/press/stylesheet.tag.(line:37)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
        ... 11 more
10 Oct 2010 11:07:47,356 ERROR ~

**Comment by dirkmc** [comment]
Ok thanks, I hadn't seen the problem because I've always used absolute paths to the images when testing. It should work with relative paths of course, I'll see if I can fix that.

**Comment by dabeeeenster** [comment]
Great - thanks. 

Great module other than that - really straightforward.

**Comment by dirkmc** [comment]
I thought about it and I decided that it's not really worth it for press to try to correct relative image urls. The problem is that the location of the compressed files is configurable, and you also have to make an assumption about the location of the css file which isn't possible when people use modules. Then there's the complexity of recognizing and replacing relative urls with the correct path.

Instead I've just added a comment to the documentation saying you should use absolute urls.
